[package]
name = "bank"
version = "0.0.1"
edition = "legacy" # edition = "legacy" to use legacy (pre-2024) Move
authors = ["Michael Roberts (michael.techroberts@gmail.com)"]      
# license = "MIT"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "framework/devnet" }

[addresses]
bank = "0x0"

